export const FETCH_POST = 'app/Blog/FETCH_POST'
export const FETCH_POST_IF_NEEDED = 'app/Blog/FETCH_POST_IF_NEEDED'

export const FETCH_POSTS = 'app/Blog/FETCH_POSTS'
export const FETCH_POSTS_IF_NEEDED = 'app/Blog/FETCH_POSTS_IF_NEEDED'

export const SET_POSTS_BY_CATEGORY_CURRENT_CATEGORY_SLUG = 'app/Blog/SET_POSTS_BY_CATEGORY_CURRENT_CATEGORY_SLUG'
export const FETCH_POSTS_BY_CATEGORY = 'app/Blog/FETCH_POSTS_BY_CATEGORY'
export const FETCH_POSTS_BY_CATEGORY_IF_NEEDED = 'app/Blog/FETCH_POSTS_BY_CATEGORY_IF_NEEDED'

export const SET_POSTS_BY_CATEGORY_CURRENT_TAG_SLUG = 'app/Blog/SET_POSTS_BY_CATEGORY_CURRENT_TAG_SLUG'
