# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:37
from __future__ import unicode_literals

from django.db import migrations


def set_modified_by_from_created_by(apps, schema_editor):
    Snippet = apps.get_model('app.Snippet')
    for snippet in Snippet.objects.all():
        snippet.modified_by = snippet.created_by
        snippet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170628_1933'),
    ]

    operations = [
        migrations.RunPython(set_modified_by_from_created_by),
    ]
