# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 23:08
from __future__ import unicode_literals

import app.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170709_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='Slug')),
                ('publish_date', models.DateField(verbose_name='Publish Date')),
                ('last_updated', models.DateTimeField(verbose_name='Last Updated')),
                ('file_path', models.FilePathField(path='/home/brian/dev/django/drf-react-boilerplate/posts', verbose_name='File Path')),
                ('is_public', models.BooleanField(default=True)),
                ('html', models.TextField(verbose_name='HTML')),
                ('preview', models.TextField(null=True, verbose_name='Preview')),
                ('categories', models.ManyToManyField(related_name='posts', to='app.Category')),
                ('created_by', models.ForeignKey(default=app.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(default=app.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ('-publish_date', '-last_updated'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='app.Tag'),
        ),
    ]
