# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170709_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview',
        ),
    ]
