# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_make_category_posts_one_to_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
