# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from pygments import highlight
from pygments.formatters.html import HtmlFormatter
from pygments.lexers import get_lexer_by_name


def get_highlight_for_snippet(snippet):
    lexer = get_lexer_by_name(snippet.language)
    formatter = HtmlFormatter(style=snippet.style,
                              linenos='table' if snippet.line_nums else False,
                              full=True,
                              title=snippet.title)
    return highlight(snippet.code, lexer, formatter)


def update_snippets(apps, schema_editor):
    Snippet = apps.get_model('snippets', 'Snippet')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User.objects.first()
    for snippet in Snippet.objects.all():
        snippet.created_by = user
        snippet.highlighted = get_highlight_for_snippet(snippet)
        snippet.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0002_auto_20170628_1407'),
    ]

    operations = [
        migrations.RunPython(update_snippets)
    ]
